theme = "iroaseta"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor]
auto-pairs = false # defaults to `true`
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

