[language-server.rust-analyzer]
command = "rust-analyzer"
[[language]]
name = "rust"
scope = "source.rs"
file-types = ["rs", {glob = "cargo.toml"}]
auto-format = true
language-servers = [ { name = "rust-analyzer"} ]


[language-server.elixir-ls]
command = "elixir-ls"
[[language]]
name = "elixir"
scope = "source.ex"
file-types = ["ex, hex"]
auto-format = true
language-servers = [ { name = "elixir-ls"} ]


[language-server.gopls]
command = "gopls"
[language-server.gofmt]
command = "gofmt"
[[language]]
name = "go"
scope = "source.go"
file-types = ["go", { glob = "go.mod" }]
auto-format = true
language-servers = [ { name = "gofmt", only-features = [ "format" ] }, "gopls" ]


[language-server.zls]
command = "zls"
[[language]]
name = "zig"
scope = "source.zig"
file-types = ["zig"]
auto-format = true
language-servers = [ { name = "zls"} ]


[language-server.helm-ls]
command = "helm-ls"
[[language]]
name = "helm"
scope = "source.helm"
file-types = ["yaml", "yml"]
auto-format = true
language-servers = [ { name = "helm-ls"} ]


[language-server.terraform-ls]
command = "terraform-ls"
args = ["serve", "-log-file", "/dev/null"]
[[language]]
name = "terraform"
scope = "source.tf"
file-types = ["tf", "tfvars"]
auto-format = true
language-servers = [ { name = "terraform-ls"} ]


[language-server.clojure-lsp]
command = "clojure-lsp"
[[language]]
name = "clojure"
scope = "source.clj"
file-types = ["clj", "cljs", "edn"]
auto-format = true
language-servers = [ { name = "clojure-ls"} ]


[language-server.pyright]
command = "basedpyright"
[language-server.black]
command = "black"
[[language]]
name = "bash"
auto-format = true
scope = "source.py"
file-types = ["py", {glob = "pyproject.toml"}]
language-servers = [ { name = "black", only-features = [ "format" ] }, "pyright" ]


[language-server.typescript-ls]
command = "bintypescript-language-server"
[[language]]
name = "typescript"
scope = "source.ts"
file-types = ["ts, js"]
auto-format = true
language-servers = [ { name = "typescript-ls"} ]


[language-server.bash-ls]
command = "bash-language-server"
[[language]]
name = "bash"
scope = "source.bash"
file-types = ["sh", "tftpl"]
shebangs = ["bash"]
auto-format = true
language-servers = [ { name = "bash-ls"} ]


[language-server.dockerfile-ls]
command = "dockerfile-language-server"
[[language]]
name = "dockerfile"
scope = "source.dockerfile"
file-types = ["dockerfile", {glob = "Dockerfile"}]
auto-format = true
language-servers = [ { name = "dockerfile-ls"} ]


[language-server.json-ls]
command = "vscode-json-language-server"
[[language]]
name = "json"
scope = "source.json"
file-types = ["json"]
auto-format = true
language-servers = [ { name = "json-ls"} ]


[language-server.yaml-ls]
command = "yaml-language-server"
[[language]]
name = "yaml"
scope = "source.yaml"
file-types = ["yaml"]
auto-format = true
language-servers = [ { name = "yaml-ls"} ]
